### ISSUE TITLE
cool stuff!

### ISSUE THREAD

**Issue by naxIO** [GenaSG/UnityUnetMovement#1]
very cool stuff, thanks for this!

Do you plan to add more things? like damage, respawn etc?

**Comment by GenaSG** [comment]
urw
Don't have any plans to update this project. At least for now.
Probably I'll start another project with a bit different approach. Will be server authoritative as well.
This one has a big downside, it doesn't  handle collider changes. So, for example, vaulting over obstacle would be choppy.

**Comment by naxIO** [comment]
I see. Still interesting. I just tried the client and server, with network simulation on the client, 100ms and 2,5% packet loss. Game didn't like it so much. 

You mind find this interesting:
https://www.assetstore.unity3d.com/en/#!/content/14984

Will be updated to UNet etc end of July (i'm not the author)

**Comment by naxIO** [comment]
I'm trying to get a auth. client side predicted and lag compensated FPS for Unity together. Still hard somehow. Unreal works out of the box but not giving up 💃

**Comment by GenaSG** [comment]
As far as I remember there is an issue with network simulation. It lags and fails.
I can play my project on 100ms without any problems but as soon as I try to use network simulator it fails miserably.
I see a lot of stories where devs move from Unity to UE because of networking. I still don't understand that. Why there isn't any official fps/tps server authoritative example from unity? 

What I end up with. Generalised  client server model like UT2004 had. Basically same cod running on all clients. Inputs synced up via network. Things that has to be checked controlled by server.

Thanks for the link, btw:)

**Comment by naxIO** [comment]
Well it seems networking is just something where unity does not work well. More like: you wanna do a 2D smartphone app - unity. Heavy fps - unreal. Sad. For unity there are few examples like "the forest" using closed source third party framework bolt. Photon is okay but not what I wanted. Forge networking is quite good but has no hitbox rewinding yet. Chatted with a lof of unity fps guys, few actually get it to a high level networking code. I think I want to pull of a public open source networked fps where a lot of smart guys contribute. For the sake of the unity community. Dont wanna seitch to UE its nice but feels so overkill/heavy.
